### PR TITLE
New run.sh

### PR DESCRIPTION
**Pull request by KwadFan**
Checks Environment for missing Files and
do a select Menu for multiple Images,
otherwise will autodetect,
Added some Options in script to manipulate
qemu-system-arm behavior.

If this is not wanted this way, feel free to delete :)
Great Job, I love the Klipper Eco System!
Regards Stephan aka KwadFan

### CODE REVIEW

**Comment by raymondh2** [comment]
@prg3 What do you think of this. I'm not familiar with this code to begin with

**Comment by prg3** [comment]
Looks good to me, lots of cleaner. Would like to know that it works on Mac and Linux fine before I'd call it good, but it definitely cleans up my code

**Comment by raymondh2** [comment]
Works good on Linux. I have no Mac to test with.

**Comment by prg3** [comment]
I'll try to run a test tonight

**Pull request merged**
