### PR TITLE
Add MainsailOS CLI updater module

### PR DESCRIPTION
**Pull request by Nomsplease**
Add a CLI updater script to check and update klipper and moonraker. Addition of Mainsail updates will be added once a method to determine version of mainsail for the check is found.

### CODE REVIEW

**Comment by cadriel** [comment]
This looks super cool.. 

re: client, is it worth considering supporting many?

**Comment by raymondh2** [comment]
I think it would be worth being able to support any major client that uses Moonraker. Both Fluidd and Mainsail.

**Comment by Nomsplease** [comment]
> I think it would be worth being able to support any major client that uses Moonraker. Both Fluidd and Mainsail.

Agreed, we would just need a way to programmatically access the current installed version to check against and verify it is up to date or needs to be updated. This is more of a stop gap until this gets pushed into Moonraker.

**Comment by raymondh2** [comment]
Couple of suggestions. I would recommend stopping each service prior to running a git pull and starting after that is complete vs restarting the service at the end.

**Comment by Nomsplease** [comment]
> Couple of suggestions. I would recommend stopping each service prior to running a git pull and starting after that is complete vs restarting the service at the end.

Good catch, implemented in new commit

**Pull request merged**
